### ISSUE TITLE
Missing REST MJM compiler sercice

### ISSUE THREAD

**Issue by michael-bouvy** [assoconnect/mjml-bundle#5]
After following the documentation regarding usage of a REST API, I have an error during cache warmup:
 
```
The service "assoconnect_mjml.compiler" has a dependency on a non-existent service "assoconnect_mjml.rest_mjml_compiler".
```

I eventually fixed it adding the following lines to my `services.yaml`:

```yaml
services:
    ...
    assoconnect_mjml.rest_mjml_compiler:
        class: Assoconnect\MJMLBundle\Compiler\RestMjmlCompiler
        arguments:
            $client: "@assoconnect_mjml.rest_mjml_compiler_client"
```

Am I doing something wrong or are those lines actually missing from the bundle's `services.yaml`?

Thanks for the great work!
